import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio of Seoyoon',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className="navBar">
              <Link className="navFont" href="/">
                Home
              </Link>
              <Link className="navFont" href="/project">
                Project
              </Link>
              <Link className="navFont" href="/education">
                E.T.C
              </Link>
          </div>
          <hr className="navLine" />
        </div>
        <div className="bodyText">{children}</div>
      </body>
    </html>
  )
}
